title: My Data Science Workstation
description: Docker image with all you need for data science.
author: Israel Oliveira <prof.israel@gmail.com>
version: 2.3.1-rapids
PORT_JUPYTERLAB: 8888
PORT_STREAMLIT: 8501
PORT_FREE: 8090
APP_NAME: my-ds
CONTAINER_NAME: ws-rapids
BASE_IMAGE_NAME: rapidsai/base
BASE_IMAGE_TAG: 24.12-cuda11.8-py3.11-amd64
SHM_SIZE: 30g
DOCKER_HOST: tcp://docker:2375
DOCKER_ACCOUNT: ysraell
